# Generated by Django 6.0.6 on 2026-06-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='diff_report',
            field=models.TextField(blank=True),
        ),
    ]
